version: '3.4'

services:
  # mood-library-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: mood-library-api
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - ConnectionStrings__Database=User ID=postgres;Password=postgres;Host=mood-library-db;Port=5432;Database=postgres;Pooling=true;
  #     - ASPNETCORE_URLS=http://+:80
  #   depends_on:
  #     - mood-library-db

  mood-library-db:
    image: postgres:latest
    container_name: mood-library-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data

volumes:
  app_data:
